# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b812e367d10154d14be139ae3b571ade400d9f6757194ea90cfef25c75e665e49fe62e985a0187e580f13f79efdeb045a0183f5eab79ad3ebe9c7d123ac26387

test:
  secret_key_base: eda15ef031e04793d6b6f67985a8dbc3481b813e0e8a7e27b81fa4120fe48c6b16d46cf02dbfa774cd2f2ed545bfd0dc3a4245ec0182552a483bc04e63a97c96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
